# Generated by Django 5.2.8 on 2025-12-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
