# Generated by Django 6.0 on 2025-12-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_coursestudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestudent',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
