# Generated by Django 6.0 on 2025-12-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_coursestudent_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='simage',
            field=models.ImageField(blank=True, default='Default.jpg', null=True, upload_to='uploads/'),
        ),
    ]
